version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cfarm-fem-app:v2
    container_name: fem_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_NAME: "CFARM FEM System"
      APP_ENV: production
      APP_KEY: "base64:PYR5HggloJHaQDjmlFUoQ/dWyrS7ovIpOS/vHA3NNQ4="
      APP_DEBUG: "true"
      APP_URL: "http://192.168.7.3:8019"
      LOG_CHANNEL: stderr
      DB_CONNECTION: mysql
      DB_HOST: 192.168.7.3
      DB_PORT: 3308
      DB_DATABASE: fire_extinguisher_db
      DB_USERNAME: itadmin
      DB_PASSWORD: "Noipalee@09"
    networks:
      - fem_network

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: cfarm-fem-webserver:v2
    container_name: fem_webserver
    restart: unless-stopped
    ports:
      - "8019:80"
    networks:
      - fem_network
    depends_on:
      - app
      
  scheduler:
    image: cfarm-fem-app:v2
    container_name: fem_scheduler
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan schedule:work
    environment:
      APP_NAME: "CFARM FEM System"
      APP_ENV: production
      APP_KEY: "base64:PYR5HggloJHaQDjmlFUoQ/dWyrS7ovIpOS/vHA3NNQ4="
      APP_DEBUG: "true"
      APP_URL: "http://192.168.7.3:8019"
      LOG_CHANNEL: stderr
      DB_CONNECTION: mysql
      DB_HOST: 192.168.7.3
      DB_PORT: 3308
      DB_DATABASE: fire_extinguisher_db
      DB_USERNAME: itadmin
      DB_PASSWORD: "Noipalee@09"
    networks:
      - fem_network
    depends_on:
      - app

networks:
  fem_network:
    driver: bridge
