version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fem_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 192.168.7.3
      DB_PORT: 3308
      DB_DATABASE: fire_extinguisher_db
      DB_USERNAME: itadmin
      DB_PASSWORD: Noipalee@09
    networks:
      - fem_network

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: fem_webserver
    restart: unless-stopped
    ports:
      - "8019:80"
    networks:
      - fem_network
    depends_on:
      - app
      
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fem_scheduler
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan schedule:work
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 192.168.7.3
      DB_PORT: 3308
      DB_DATABASE: fire_extinguisher_db
      DB_USERNAME: itadmin
      DB_PASSWORD: Noipalee@09
    networks:
      - fem_network

networks:
  fem_network:
    driver: bridge
